---
- name: Transfer and map virtual file on all worker nodes
  hosts: all
  become: yes

  tasks:
    - name: Ensure destination directory exists
      file:
        path: /etc/postfix
        state: directory

    - name: Transfer the virtual file to the worker nodes
      copy:
        src: ./virtual
        dest: /etc/postfix/virtual
        owner: root
        group: root
        mode: '0644'

    - name: Map the virtual file in Postfix configuration
      lineinfile:
        path: /etc/postfix/main.cf
        regexp: 'virtual_alias_maps ='
        line: 'virtual_alias_maps = hash:/etc/postfix/virtual'
        state: present

    - name: Run postmap to update virtual file hash
      command: postmap /etc/postfix/virtual
      args:
        creates: /etc/postfix/virtual.db

    - name: Restart Postfix service to apply changes
      service:
        name: postfix
        state: reloaded

