DELETE FROM mailbox WHERE username = 'eva.goldstein@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'eva.goldstein@flatfeeloans.com' OR forwarding = 'eva.goldstein@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'edith.erickson@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'edith.erickson@flatfeeloans.com' OR forwarding = 'edith.erickson@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'amy.lee@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'amy.lee@flatfeeloans.com' OR forwarding = 'amy.lee@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'jill.bruns@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'jill.bruns@flatfeeloans.com' OR forwarding = 'jill.bruns@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'gertrude.jones@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'gertrude.jones@flatfeeloans.com' OR forwarding = 'gertrude.jones@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'sandy.lopez@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'sandy.lopez@flatfeeloans.com' OR forwarding = 'sandy.lopez@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'jeane.gustafson@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'jeane.gustafson@flatfeeloans.com' OR forwarding = 'jeane.gustafson@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'essie.duncan@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'essie.duncan@flatfeeloans.com' OR forwarding = 'essie.duncan@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'frances.rhodes@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'frances.rhodes@flatfeeloans.com' OR forwarding = 'frances.rhodes@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'june.holt@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'june.holt@flatfeeloans.com' OR forwarding = 'june.holt@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'patricia.wiles@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'patricia.wiles@flatfeeloans.com' OR forwarding = 'patricia.wiles@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'donna.ford@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'donna.ford@flatfeeloans.com' OR forwarding = 'donna.ford@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'jean.grant@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'jean.grant@flatfeeloans.com' OR forwarding = 'jean.grant@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'christoper.garner@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'christoper.garner@flatfeeloans.com' OR forwarding = 'christoper.garner@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'eva.weaver@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'eva.weaver@flatfeeloans.com' OR forwarding = 'eva.weaver@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'james.barker@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'james.barker@flatfeeloans.com' OR forwarding = 'james.barker@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'doris.noonan@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'doris.noonan@flatfeeloans.com' OR forwarding = 'doris.noonan@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'arvilla.turner@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'arvilla.turner@flatfeeloans.com' OR forwarding = 'arvilla.turner@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'carolyn.collins@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'carolyn.collins@flatfeeloans.com' OR forwarding = 'carolyn.collins@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'david.stuart@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'david.stuart@flatfeeloans.com' OR forwarding = 'david.stuart@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'ruby.blake@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'ruby.blake@flatfeeloans.com' OR forwarding = 'ruby.blake@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'chantal.sutton@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'chantal.sutton@flatfeeloans.com' OR forwarding = 'chantal.sutton@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'garfield.jackson@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'garfield.jackson@flatfeeloans.com' OR forwarding = 'garfield.jackson@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'april.young@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'april.young@flatfeeloans.com' OR forwarding = 'april.young@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'gina.simons@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'gina.simons@flatfeeloans.com' OR forwarding = 'gina.simons@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'carla.stinson@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'carla.stinson@flatfeeloans.com' OR forwarding = 'carla.stinson@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'gloria.perkins@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'gloria.perkins@flatfeeloans.com' OR forwarding = 'gloria.perkins@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'thomas.bryant@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'thomas.bryant@flatfeeloans.com' OR forwarding = 'thomas.bryant@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'jayden.kossak@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'jayden.kossak@flatfeeloans.com' OR forwarding = 'jayden.kossak@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'brianna.milford@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'brianna.milford@flatfeeloans.com' OR forwarding = 'brianna.milford@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'bella.mcilwraith@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'bella.mcilwraith@flatfeeloans.com' OR forwarding = 'bella.mcilwraith@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'ali.allcot@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'ali.allcot@flatfeeloans.com' OR forwarding = 'ali.allcot@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'ellie.arnot@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'ellie.arnot@flatfeeloans.com' OR forwarding = 'ellie.arnot@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'claire.crombie@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'claire.crombie@flatfeeloans.com' OR forwarding = 'claire.crombie@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'amber.paschke@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'amber.paschke@flatfeeloans.com' OR forwarding = 'amber.paschke@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'elizabeth.desalis@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'elizabeth.desalis@flatfeeloans.com' OR forwarding = 'elizabeth.desalis@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'natasha.henty@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'natasha.henty@flatfeeloans.com' OR forwarding = 'natasha.henty@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'jeremy.crofts@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'jeremy.crofts@flatfeeloans.com' OR forwarding = 'jeremy.crofts@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'ashton.bennelong@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'ashton.bennelong@flatfeeloans.com' OR forwarding = 'ashton.bennelong@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'daniel.macneil@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'daniel.macneil@flatfeeloans.com' OR forwarding = 'daniel.macneil@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'alica.fullerton@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'alica.fullerton@flatfeeloans.com' OR forwarding = 'alica.fullerton@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'isabella.mcalroy@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'isabella.mcalroy@flatfeeloans.com' OR forwarding = 'isabella.mcalroy@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'ashley.mcclemans@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'ashley.mcclemans@flatfeeloans.com' OR forwarding = 'ashley.mcclemans@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'cameron.field@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'cameron.field@flatfeeloans.com' OR forwarding = 'cameron.field@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'erin.neild@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'erin.neild@flatfeeloans.com' OR forwarding = 'erin.neild@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'christopher.wilfred@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'christopher.wilfred@flatfeeloans.com' OR forwarding = 'christopher.wilfred@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'ali.griffin@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'ali.griffin@flatfeeloans.com' OR forwarding = 'ali.griffin@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'charlotte.eve@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'charlotte.eve@flatfeeloans.com' OR forwarding = 'charlotte.eve@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'lucy.stansfield@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'lucy.stansfield@flatfeeloans.com' OR forwarding = 'lucy.stansfield@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'sarah.micklem@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'sarah.micklem@flatfeeloans.com' OR forwarding = 'sarah.micklem@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'hugo.purves@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'hugo.purves@flatfeeloans.com' OR forwarding = 'hugo.purves@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'mary.pridgen@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'mary.pridgen@flatfeeloans.com' OR forwarding = 'mary.pridgen@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'jeannette.cox@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'jeannette.cox@flatfeeloans.com' OR forwarding = 'jeannette.cox@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'bernice.moore@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'bernice.moore@flatfeeloans.com' OR forwarding = 'bernice.moore@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'elva.levitt@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'elva.levitt@flatfeeloans.com' OR forwarding = 'elva.levitt@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'grace.mullen@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'grace.mullen@flatfeeloans.com' OR forwarding = 'grace.mullen@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'aaron.rivera@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'aaron.rivera@flatfeeloans.com' OR forwarding = 'aaron.rivera@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'ezra.carlisle@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'ezra.carlisle@flatfeeloans.com' OR forwarding = 'ezra.carlisle@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'dong.brune@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'dong.brune@flatfeeloans.com' OR forwarding = 'dong.brune@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'erin.obrien@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'erin.obrien@flatfeeloans.com' OR forwarding = 'erin.obrien@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'frederick.stiffler@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'frederick.stiffler@flatfeeloans.com' OR forwarding = 'frederick.stiffler@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'donna.burrows@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'donna.burrows@flatfeeloans.com' OR forwarding = 'donna.burrows@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'anthony.skillman@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'anthony.skillman@flatfeeloans.com' OR forwarding = 'anthony.skillman@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'bruce.mcclellan@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'bruce.mcclellan@flatfeeloans.com' OR forwarding = 'bruce.mcclellan@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'andrea.ring@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'andrea.ring@flatfeeloans.com' OR forwarding = 'andrea.ring@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'anthony.bunch@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'anthony.bunch@flatfeeloans.com' OR forwarding = 'anthony.bunch@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'anna.owens@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'anna.owens@flatfeeloans.com' OR forwarding = 'anna.owens@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'haley.kelly@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'haley.kelly@flatfeeloans.com' OR forwarding = 'haley.kelly@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'carrie.torpey@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'carrie.torpey@flatfeeloans.com' OR forwarding = 'carrie.torpey@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'bruce.pierce@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'bruce.pierce@flatfeeloans.com' OR forwarding = 'bruce.pierce@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'anna.lagrone@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'anna.lagrone@flatfeeloans.com' OR forwarding = 'anna.lagrone@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'dorothy.antonio@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'dorothy.antonio@flatfeeloans.com' OR forwarding = 'dorothy.antonio@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'alice.gilbert@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'alice.gilbert@flatfeeloans.com' OR forwarding = 'alice.gilbert@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'evelin.gunter@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'evelin.gunter@flatfeeloans.com' OR forwarding = 'evelin.gunter@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'anna.tapley@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'anna.tapley@flatfeeloans.com' OR forwarding = 'anna.tapley@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'amanda.wilson@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'amanda.wilson@flatfeeloans.com' OR forwarding = 'amanda.wilson@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'elise.wilkins@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'elise.wilkins@flatfeeloans.com' OR forwarding = 'elise.wilkins@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'esperanza.harjo@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'esperanza.harjo@flatfeeloans.com' OR forwarding = 'esperanza.harjo@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'addie.harney@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'addie.harney@flatfeeloans.com' OR forwarding = 'addie.harney@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'cynthia.fox@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'cynthia.fox@flatfeeloans.com' OR forwarding = 'cynthia.fox@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'edna.morrow@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'edna.morrow@flatfeeloans.com' OR forwarding = 'edna.morrow@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'james.smyth@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'james.smyth@flatfeeloans.com' OR forwarding = 'james.smyth@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'christine.piper@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'christine.piper@flatfeeloans.com' OR forwarding = 'christine.piper@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'janice.rankin@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'janice.rankin@flatfeeloans.com' OR forwarding = 'janice.rankin@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'lara.mcmillan@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'lara.mcmillan@flatfeeloans.com' OR forwarding = 'lara.mcmillan@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'jill.munoz@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'jill.munoz@flatfeeloans.com' OR forwarding = 'jill.munoz@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'adam.bartlett@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'adam.bartlett@flatfeeloans.com' OR forwarding = 'adam.bartlett@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'ellie.caverly@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'ellie.caverly@flatfeeloans.com' OR forwarding = 'ellie.caverly@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'bertha.vierra@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'bertha.vierra@flatfeeloans.com' OR forwarding = 'bertha.vierra@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'bobbie.frierson@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'bobbie.frierson@flatfeeloans.com' OR forwarding = 'bobbie.frierson@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'charlene.meyer@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'charlene.meyer@flatfeeloans.com' OR forwarding = 'charlene.meyer@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'carl.laroche@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'carl.laroche@flatfeeloans.com' OR forwarding = 'carl.laroche@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'david.mahaffey@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'david.mahaffey@flatfeeloans.com' OR forwarding = 'david.mahaffey@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'christina.moses@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'christina.moses@flatfeeloans.com' OR forwarding = 'christina.moses@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'rosetta.nicholson@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'rosetta.nicholson@flatfeeloans.com' OR forwarding = 'rosetta.nicholson@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'debra.basile@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'debra.basile@flatfeeloans.com' OR forwarding = 'debra.basile@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'clarence.hammer@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'clarence.hammer@flatfeeloans.com' OR forwarding = 'clarence.hammer@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'bessie.luman@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'bessie.luman@flatfeeloans.com' OR forwarding = 'bessie.luman@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'david.mooney@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'david.mooney@flatfeeloans.com' OR forwarding = 'david.mooney@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'albina.springer@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'albina.springer@flatfeeloans.com' OR forwarding = 'albina.springer@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'alice.macdonald@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'alice.macdonald@flatfeeloans.com' OR forwarding = 'alice.macdonald@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'curtis.maes@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'curtis.maes@flatfeeloans.com' OR forwarding = 'curtis.maes@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'emily.jansen@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'emily.jansen@flatfeeloans.com' OR forwarding = 'emily.jansen@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'bonita.degraw@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'bonita.degraw@flatfeeloans.com' OR forwarding = 'bonita.degraw@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'gladys.lopez@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'gladys.lopez@flatfeeloans.com' OR forwarding = 'gladys.lopez@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'betty.sellner@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'betty.sellner@flatfeeloans.com' OR forwarding = 'betty.sellner@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'clifford.pruitt@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'clifford.pruitt@flatfeeloans.com' OR forwarding = 'clifford.pruitt@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'brian.bad@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'brian.bad@flatfeeloans.com' OR forwarding = 'brian.bad@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'betty.renfrow@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'betty.renfrow@flatfeeloans.com' OR forwarding = 'betty.renfrow@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'annie.bright@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'annie.bright@flatfeeloans.com' OR forwarding = 'annie.bright@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'edwin.robins@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'edwin.robins@flatfeeloans.com' OR forwarding = 'edwin.robins@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'dorothy.santee@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'dorothy.santee@flatfeeloans.com' OR forwarding = 'dorothy.santee@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'sandra.shelton@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'sandra.shelton@flatfeeloans.com' OR forwarding = 'sandra.shelton@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'charlotte.cummings@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'charlotte.cummings@flatfeeloans.com' OR forwarding = 'charlotte.cummings@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'diana.lopez@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'diana.lopez@flatfeeloans.com' OR forwarding = 'diana.lopez@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'buford.smith@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'buford.smith@flatfeeloans.com' OR forwarding = 'buford.smith@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'dorothy.phillips@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'dorothy.phillips@flatfeeloans.com' OR forwarding = 'dorothy.phillips@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'adella.barker@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'adella.barker@flatfeeloans.com' OR forwarding = 'adella.barker@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'craig.mcclure@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'craig.mcclure@flatfeeloans.com' OR forwarding = 'craig.mcclure@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'dorothy.james@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'dorothy.james@flatfeeloans.com' OR forwarding = 'dorothy.james@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'debra.gross@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'debra.gross@flatfeeloans.com' OR forwarding = 'debra.gross@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'irene.lindsey@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'irene.lindsey@flatfeeloans.com' OR forwarding = 'irene.lindsey@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'angel.schaefer@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'angel.schaefer@flatfeeloans.com' OR forwarding = 'angel.schaefer@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'brenda.wong@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'brenda.wong@flatfeeloans.com' OR forwarding = 'brenda.wong@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'anastasia.ayers@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'anastasia.ayers@flatfeeloans.com' OR forwarding = 'anastasia.ayers@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'claudia.thomas@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'claudia.thomas@flatfeeloans.com' OR forwarding = 'claudia.thomas@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'zelda.morrone@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'zelda.morrone@flatfeeloans.com' OR forwarding = 'zelda.morrone@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'amanda.studebaker@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'amanda.studebaker@flatfeeloans.com' OR forwarding = 'amanda.studebaker@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'renee.nagy@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'renee.nagy@flatfeeloans.com' OR forwarding = 'renee.nagy@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'donnie.mccants@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'donnie.mccants@flatfeeloans.com' OR forwarding = 'donnie.mccants@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'cynthia.dale@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'cynthia.dale@flatfeeloans.com' OR forwarding = 'cynthia.dale@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'kaaren.jones@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'kaaren.jones@flatfeeloans.com' OR forwarding = 'kaaren.jones@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'crystal.howell@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'crystal.howell@flatfeeloans.com' OR forwarding = 'crystal.howell@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'gilda.ventimiglia@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'gilda.ventimiglia@flatfeeloans.com' OR forwarding = 'gilda.ventimiglia@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'candace.gray@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'candace.gray@flatfeeloans.com' OR forwarding = 'candace.gray@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'ginger.perez@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'ginger.perez@flatfeeloans.com' OR forwarding = 'ginger.perez@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'alberta.simmons@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'alberta.simmons@flatfeeloans.com' OR forwarding = 'alberta.simmons@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'elayne.lizarraga@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'elayne.lizarraga@flatfeeloans.com' OR forwarding = 'elayne.lizarraga@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'estelle.johnson@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'estelle.johnson@flatfeeloans.com' OR forwarding = 'estelle.johnson@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'eugene.zabala@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'eugene.zabala@flatfeeloans.com' OR forwarding = 'eugene.zabala@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'julie.pruneda@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'julie.pruneda@flatfeeloans.com' OR forwarding = 'julie.pruneda@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'hiram.martin@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'hiram.martin@flatfeeloans.com' OR forwarding = 'hiram.martin@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'irene.davis@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'irene.davis@flatfeeloans.com' OR forwarding = 'irene.davis@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'beverly.garza@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'beverly.garza@flatfeeloans.com' OR forwarding = 'beverly.garza@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'jonathon.davis@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'jonathon.davis@flatfeeloans.com' OR forwarding = 'jonathon.davis@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'john.middleton@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'john.middleton@flatfeeloans.com' OR forwarding = 'john.middleton@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'betty.hume@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'betty.hume@flatfeeloans.com' OR forwarding = 'betty.hume@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'darlene.mackay@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'darlene.mackay@flatfeeloans.com' OR forwarding = 'darlene.mackay@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'jack.hale@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'jack.hale@flatfeeloans.com' OR forwarding = 'jack.hale@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'donald.brooks@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'donald.brooks@flatfeeloans.com' OR forwarding = 'donald.brooks@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'celia.freese@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'celia.freese@flatfeeloans.com' OR forwarding = 'celia.freese@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'aida.goff@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'aida.goff@flatfeeloans.com' OR forwarding = 'aida.goff@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'barbara.weaver@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'barbara.weaver@flatfeeloans.com' OR forwarding = 'barbara.weaver@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'charlotte.gobert@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'charlotte.gobert@flatfeeloans.com' OR forwarding = 'charlotte.gobert@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'elnora.berry@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'elnora.berry@flatfeeloans.com' OR forwarding = 'elnora.berry@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'anna.skidmore@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'anna.skidmore@flatfeeloans.com' OR forwarding = 'anna.skidmore@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'betty.pearce@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'betty.pearce@flatfeeloans.com' OR forwarding = 'betty.pearce@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'beth.miller@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'beth.miller@flatfeeloans.com' OR forwarding = 'beth.miller@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'alice.garcia@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'alice.garcia@flatfeeloans.com' OR forwarding = 'alice.garcia@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'cassandra.todd@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'cassandra.todd@flatfeeloans.com' OR forwarding = 'cassandra.todd@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'jesus.kaplan@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'jesus.kaplan@flatfeeloans.com' OR forwarding = 'jesus.kaplan@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'ada.johnson@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'ada.johnson@flatfeeloans.com' OR forwarding = 'ada.johnson@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'adriana.partida@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'adriana.partida@flatfeeloans.com' OR forwarding = 'adriana.partida@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'alicia.johns@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'alicia.johns@flatfeeloans.com' OR forwarding = 'alicia.johns@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'doris.myers@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'doris.myers@flatfeeloans.com' OR forwarding = 'doris.myers@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'belinda.graham@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'belinda.graham@flatfeeloans.com' OR forwarding = 'belinda.graham@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'craig.esteban@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'craig.esteban@flatfeeloans.com' OR forwarding = 'craig.esteban@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'donna.wu@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'donna.wu@flatfeeloans.com' OR forwarding = 'donna.wu@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'dorothy.stewart@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'dorothy.stewart@flatfeeloans.com' OR forwarding = 'dorothy.stewart@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'deanna.zeigler@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'deanna.zeigler@flatfeeloans.com' OR forwarding = 'deanna.zeigler@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'collette.dow@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'collette.dow@flatfeeloans.com' OR forwarding = 'collette.dow@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'elizabeth.rossi@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'elizabeth.rossi@flatfeeloans.com' OR forwarding = 'elizabeth.rossi@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'ruth.duke@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'ruth.duke@flatfeeloans.com' OR forwarding = 'ruth.duke@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'dewey.green@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'dewey.green@flatfeeloans.com' OR forwarding = 'dewey.green@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'charles.bray@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'charles.bray@flatfeeloans.com' OR forwarding = 'charles.bray@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'christy.calabro@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'christy.calabro@flatfeeloans.com' OR forwarding = 'christy.calabro@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'brandy.bailey@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'brandy.bailey@flatfeeloans.com' OR forwarding = 'brandy.bailey@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'kristine.harvey@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'kristine.harvey@flatfeeloans.com' OR forwarding = 'kristine.harvey@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'brenda.childs@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'brenda.childs@flatfeeloans.com' OR forwarding = 'brenda.childs@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'christopher.miller@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'christopher.miller@flatfeeloans.com' OR forwarding = 'christopher.miller@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'alicia.gonzales@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'alicia.gonzales@flatfeeloans.com' OR forwarding = 'alicia.gonzales@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'harold.gosney@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'harold.gosney@flatfeeloans.com' OR forwarding = 'harold.gosney@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'sarah.perez@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'sarah.perez@flatfeeloans.com' OR forwarding = 'sarah.perez@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'carmel.freeman@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'carmel.freeman@flatfeeloans.com' OR forwarding = 'carmel.freeman@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'carl.mercer@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'carl.mercer@flatfeeloans.com' OR forwarding = 'carl.mercer@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'christine.taylor@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'christine.taylor@flatfeeloans.com' OR forwarding = 'christine.taylor@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'gloria.frank@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'gloria.frank@flatfeeloans.com' OR forwarding = 'gloria.frank@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'carol.cooper@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'carol.cooper@flatfeeloans.com' OR forwarding = 'carol.cooper@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'julie.espinal@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'julie.espinal@flatfeeloans.com' OR forwarding = 'julie.espinal@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'earlene.dockery@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'earlene.dockery@flatfeeloans.com' OR forwarding = 'earlene.dockery@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'cynthia.quinn@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'cynthia.quinn@flatfeeloans.com' OR forwarding = 'cynthia.quinn@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'brett.fletcher@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'brett.fletcher@flatfeeloans.com' OR forwarding = 'brett.fletcher@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'donna.hill@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'donna.hill@flatfeeloans.com' OR forwarding = 'donna.hill@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'bertha.pons@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'bertha.pons@flatfeeloans.com' OR forwarding = 'bertha.pons@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'carol.stribling@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'carol.stribling@flatfeeloans.com' OR forwarding = 'carol.stribling@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'austin.walker@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'austin.walker@flatfeeloans.com' OR forwarding = 'austin.walker@flatfeeloans.com';
DELETE FROM mailbox WHERE username = 'frank.mahurin@flatfeeloans.com';
DELETE FROM forwardings WHERE address = 'frank.mahurin@flatfeeloans.com' OR forwarding = 'frank.mahurin@flatfeeloans.com';
