---
- name: Delete users from MySQL on remote host
  hosts: all
  become: yes
  tasks:
    - name: Ensure the script is present
      copy:
        src: ./delete_senderrelay.sql
        dest: /root/delete_senderrelay.sql
        mode: '0644'

    - name: Execute the generated SQL script without MySQL login
      shell: mysql vmail < /root/delete_senderrelay.sql
