---
- name: Add domains and users in iRedMail
  hosts: all
  become: yes

  vars_files:
    - "{{ user }}"

  tasks:
    - name: Ensure /tmp directory exists
      file:
        path: /tmp
        state: directory

    - name: Generate user SQL script
      shell: bash /root/iRedMail-1.7.2/tools/create_mail_user_SQL.sh {{ item.1.username }}@{{ item.0.name }} '{{ item.1.password }}' >> /root/user.sql
      loop: "{{ lookup('subelements', domains, 'users') }}"
      loop_control:
        index_var: item_index
      register: user_sql_output
      ignore_errors: yes  # Ignore errors to prevent failure on already existing users

    - name: Add user SQL script to MySQL
      mysql_db:
        name: vmail
        state: import
        target: /root/user.sql
      when: user_sql_output is not failed
      ignore_errors: yes

