---
- name: Install iRedMail on a server
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Copy install script to remote server
      copy:
        src: ./iredmail.sh
        dest: /root/iredmail.sh
        mode: '0755'

    - name: Run the iRedMail installation script
      shell: /root/iredmail.sh
      args:
        chdir: /root
      environment:
        HOSTNAME: "{{ hostname }}"  # Pass the hostname variable to the script
      register: install_output
      ignore_errors: yes

    - name: Print installation output
      debug:
        var: install_output.stdout_lines

    - name: Print installation errors
      debug:
        var: install_output.stderr_lines

